### PR TITLE
HAPPY BIRTHDAY JAKE

### PR DESCRIPTION
**Pull request by AntonCSalvador**
here is a pr, just adds some script and a banner into the readme that we can change later

### CODE REVIEW

**Comment by JMalegni** [comment]
Just saw that you guys actually made me a birthday pr, I totally though you were joking, but anyways...

grammatical error in w0_d2 on line 450. Should read "Seems like C++ and I might be the only smart people here". Other than that, everything else looks great

**Review by JMalegni — CHANGES_REQUESTED** [review]
w0_d2 line 450 grammar issue

**Comment by WilsonGoins** [comment]
Maybe I am being stupid, but it looks like a lot of the script changed is in w0_d2. But w0_d2 is the second day of orientation, when MC has a convo in class and picks classes. These all need to be in w0_d1

**Comment by AntonCSalvador** [comment]
@WilsonGoins thats mine and @Xa-el  's bad 😭 our naming convention is wrong, but the days are technically correct

**Comment by WilsonGoins** [comment]
> @WilsonGoins thats mine and @Xa-el 's bad 😭 our naming convention is wrong, but the days are technically correct

No problem, if we change that and the grammar issue we should be good. I will reach out to Tyra and others and get the photos done ASAP and I will finalize w0_d2 script 👍

**Comment by AntonCSalvador** [comment]
@JMalegni can you rereview

**Comment by Xa-el** [comment]
@JMalegni I need green squares please accept the pr. It's not done but its progress 😊

**Pull request merged**
