### PR TITLE
Added interactive game map, animations, typos, credits, character colors, gui, and fonts

### PR DESCRIPTION
**Pull request by Xa-el**

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
w0_d0, w0_d1

**Comment by Xa-el** [comment]
LGTM

**Comment by JMalegni** [comment]
I am assuming that in before orientation the random backgrounds during the Rust vending machine choice were accidentally left in from our discussion about how to do backgrounds. Can we revert it back to the AI placeholder?

**Comment by JMalegni** [comment]
In w0_d2 line 259 there is a typo. the script says "im" and it should be "I'm"

**Comment by JMalegni** [comment]
Everything else lgtm, just  fix the previous two things and I will approve and merge

**Comment by Xa-el** [comment]
@JMalegni I have fixed the background issue for the Rust scene in before orientation. Dont worry about w0_d2 typos for now. It isnt finalized rn but it will be in the next pr.

**Review by JMalegni — APPROVED** [review]

**Comment by JMalegni** [comment]
4 am commits are wild

**Pull request merged**
