### PR TITLE
Added main menu music and credits markdown file

### PR DESCRIPTION
**Pull request by Xa-el**
Main menu music added to the game. Credits markdown file added.

### CODE REVIEW

**Comment by Xa-el** [comment]
LGTM

**Comment by nickv779** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by nickv779** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by Xa-el** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by Xa-el** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by Xa-el** [comment]
LGTM

**Comment by JMalegni** [comment]
bum commits

**Review by nickv779 — APPROVED** [review]
**L**ooks **G**ood **T**o **M**e

**Pull request merged**
