### PR TITLE
Fixed windows and added new backgrounds into the game

### PR DESCRIPTION
**Pull request by AntonCSalvador**

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
just added character sprites and replaced the temp ones.

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by AntonCSalvador** [comment]
LGTM

**Review by JMalegni — APPROVED** [review]
LGTM

**Pull request merged**
