### PR TITLE
ABLE TO MERGE. Fixed merge conflicts from OG PR

### PR DESCRIPTION
**Pull request by AntonCSalvador**
Fixed and implemented Jake's recommendation

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM

**Comment by Xa-el** [comment]
This works trust 😎

**Review by AntonCSalvador — COMMENTED** [review]
LGTM

**Review by nickv779 — APPROVED** [review]
lgtm (I didn't test it)

**Comment by JMalegni** [comment]
how did you get it fixed??

**Comment by Xa-el** [comment]
@JMalegni You actually fixed it by doing whatever you did! There was just some changes I needed to make to it since for some reason it wanted to revert to old code.

**Comment by JMalegni** [comment]
that's actually insane

**Comment by Xa-el** [comment]
Some would say it was crazy

**Pull request merged**
