### PR TITLE
Started W1_D1 Orientation and Added New Backgrounds

### PR DESCRIPTION
**Pull request by AntonCSalvador**
Added in new backgrounds and started on the week 1 orientation content. Added in the first 1/5 of the 1st orientation day stuff.

Early commits in this one are scuffed and dupes but shouldnt effect anything.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
LGTM. @JMalegni @nickv779 ??

**Review by JMalegni — COMMENTED** [review]
Does not lgtm. The art cooked, but after the lecture hall there is a call to a label that doesn't exist, crashing the game

**Comment by AntonCSalvador** [comment]
Will fix rn

**Review by JMalegni — APPROVED** [review]
LGTM, can't wait to see Java

**Pull request merged**
