### PR TITLE
Added text speed, minor changes to script, and fade transitions

### PR DESCRIPTION
**Pull request by Xa-el**
Text now moves at 30 characters per second. Minor grammatical changes were made to the pre-orientation script. Added a transition section in scripts.rpy where all future transitions will be defined and added a long fade transition.

### CODE REVIEW

**Comment by AntonCSalvador** [comment]
I think it should be faster

**Review by AntonCSalvador — CHANGES_REQUESTED** [review]
I think the time to load the text should be faster, for reference https://www.youtube.com/watch?v=msc1n57t-L8 . 

I think big positive of the moving text is more so the screen is dynamic, not necessarily for the reader bc some people read fast and it could low key be a turn off.

**Comment by AntonCSalvador** [comment]
DNLGTM

**Comment by Xa-el** [comment]
Changed the text speed to match reference!

**Review by AntonCSalvador — APPROVED** [review]
Looks good to me. tested and down to merge

**Review by AntonCSalvador — APPROVED** [review]
New new changes LGTM. Good job Sr Ren'Py Developer! @Xa-el

**Review by JMalegni — APPROVED** [review]

**Review by JMalegni — COMMENTED** [review]
looking good, we need to get the script writers to make the mean option a bit more mean

**Pull request merged**
